### ISSUE TITLE
Can't Scroll

### ISSUE THREAD

**Issue by TheXtremePerson** [chylex/Resource-Pack-Organizer#1]
I'm currently using a mac and I cannot scroll through the texture packs... I don't know why. Is it because of the fact that I'm using a mac? I see Tenebrous scrolling fine but I don't know why I can't. Please tell me what's wrong asap. Thanks!

**Comment by chylex** [comment]
What version of Minecraft?

**Comment by TheXtremePerson** [comment]
1.9.4

**Comment by TheXtremePerson** [comment]
No other mods installed in it except for Optifine

**Comment by TheXtremePerson** [comment]
and your mod of course.

**Comment by chylex** [comment]
Does it work without optifine?

**Comment by TheXtremePerson** [comment]
I just tried it and it still does not work.

**Comment by chylex** [comment]
Ok, I'll look into it later. Can't now because Forge for 1.9 doesn't work on older computers and I don't have anything better right now.

**Comment by TheXtremePerson** [comment]
Ok thanks a lot chylex!!
