### ISSUE TITLE
Resource Pack Organizer Glitch

### ISSUE THREAD

**Issue by GamerIn** [chylex/Resource-Pack-Organizer#12]
I have recently download this minecraft mod called Resource pack Organizer even tho I can just not use it I would like to use it and every time I try to switch packs It wont let me and glitches out.
![capture](https://user-images.githubusercontent.com/33606448/32702883-6423b7ea-c7bb-11e7-8bb8-7cb3cc9152c4.PNG)
Any help?

**Comment by chylex** [comment]
Does this happen without any other mods installed?

**Comment by GamerIn** [comment]
no

**Comment by chylex** [comment]
Well, can you check which mod is conflicting?

**Comment by GamerIn** [comment]
Sure Ill get to you when I can rn Im doing something but when im done Ill see which mod is.

**Comment by GamerIn** [comment]
Optifine seems to be the issue right when I put optifine in my mods folder it happens and I found another glitch where i can use the thing to scroll down the pack

**Comment by chylex** [comment]
Optifine conflicts with quite a few mods, so not sure I can do anything about that.

**Comment by GamerIn** [comment]
Okay Thanks for the help.
