### ISSUE TITLE
Resource Pack Folder Crash?

### ISSUE THREAD

**Issue by GamerIn** [chylex/Resource-Pack-Organizer#13]
![capture](https://user-images.githubusercontent.com/33606448/33046237-22c2519e-ce1e-11e7-8fcc-346e6294a2f8.PNG)
Everytime I try to open up my resource pack folder It crashes my MC any help?

**Comment by GamerIn** [comment]
Now the problem seems to be I cant open my mc crashes I can open and change my pack but my mc crashes

**Comment by chylex** [comment]
Your game is running out of memory. http://hopper.minecraft.net/help/out-of-memory/

**Comment by GamerIn** [comment]
Okay Thank you and how do I empty up my ram?

**Comment by chylex** [comment]
Read the article I linked.
