### ISSUE TITLE
I dont see the search bar or the folder in resource packs

### ISSUE THREAD

**Issue by ZipZED** [chylex/Resource-Pack-Organizer#15]
when i click on resourcepacks it just shows all of my packs no folder no search bar its like if i didnt even have the mod.

**Comment by ZipZED** [comment]
![screenshot_1](https://user-images.githubusercontent.com/34422060/33807597-1e57643a-dd8e-11e7-857f-bcd27ba63a4b.png)

**Comment by chylex** [comment]
Another mod is conflicting, if two mods try to modify the resource pack menu at the same time, then I can't do much about that.
