### ISSUE TITLE
MC crashes randomly?

### ISSUE THREAD

**Issue by GamerIn** [chylex/Resource-Pack-Organizer#16]
Just recently my mc has been crashing and I dont know why. Can anyone help?
![welps](https://user-images.githubusercontent.com/33606448/34925228-05189198-f976-11e7-988b-e5448805ddb2.PNG)

**Comment by chylex** [comment]
Post full crash report.

**Comment by GamerIn** [comment]
it does not seem to be happening now so I cant :/

**Comment by chylex** [comment]
Reopen if it happens again.

**Comment by GamerIn** [comment]
okay
