### ISSUE TITLE
Laggy When Loading Packs...

### ISSUE THREAD

**Issue by BaconGamer** [chylex/Resource-Pack-Organizer#20]
Just seems to be a problem... could you do optimization for the next update? 1.7 and 1.8 are the versions I use...

**Comment by chylex** [comment]
Only latest version of Minecraft is supported, older versions won't get any more updates, sorry. Resource packs in old MC versions are just slow, that seems to be a vanilla problem as there weren't major changes in RPO across the updates but the only reports about slowness are for old MC.

**Comment by BaconGamer** [comment]
welp...
