### ISSUE TITLE
RPO 1.1-1.3 doesn't work with custom skies, but 1.0 does

### ISSUE THREAD

**Issue by cardssss** [chylex/Resource-Pack-Organizer#22]
RPO 1.0 works but the later versions do not. The problem is because 1.0 being the old version scrolling doesn't work, you can't put folders inside of other folders and sometimes it just does not show the texture packs. I have tried removing all other mods except optifine and RPO (you need optifine for custom skies) to confirm that RPO is the problem and it is. I have no idea how coding works and the changes that you made between 1.0 and 1.1-1.3 and I do not know if you can do anything about this but if you can I would be very grateful. Thank you.

**Comment by chylex** [comment]
See https://github.com/chylex/Resource-Pack-Organizer/issues/7#issuecomment-663473975.
