### ISSUE TITLE
Optifine Problem!

### ISSUE THREAD

**Issue by Tentoxa** [chylex/Resource-Pack-Organizer#25]
Hello,
I currently have the problem that when I use Optifine a texture bug occurs. So, if I have Optifine in my mod folder and on Resourcepack Organiszer for 1.8.9, then I don't see the textures from the texture pack, but from the default minecraft pack. How do I fix this? I've already looked but when I remove optifine from my mod folder the bug is no longer there, only if I have it inside.

Best Regards,
Philipp

**Comment by chylex** [comment]
1.8.9 is no longer supported, and since Optifine is closed source it's more difficult to make it compatible with other mods.

**Comment by Tentoxa** [comment]
Ok, but can you tell me another mod that serves the same purpose, just for the 1.8.9.

**Comment by chylex** [comment]
I don't think anyone else made one.
