### ISSUE TITLE
It takes me about 30 seconds just for the resource pack folder to load in game

### ISSUE THREAD

**Issue by Starzzy** [chylex/Resource-Pack-Organizer#3]
In 1.8.9 i can hit resource packs and it will load within like 5 seconds most in 1.7 it takes me atleast 28 seconds just for it to pop up which makes no sense and is very annoying and basically forces me to use the same pack for something that i don't want to use it for. please fix this or tell me how to fix it.

**Comment by chylex** [comment]
Don't know. If it's only happening in 1.7.10, then 1.7.10 is probably just slow. RPO shsouldn't have any major changes across Minecraft versions that would cause a certain version to be slow.

**Comment by chylex** [comment]
1.7.10 has not been supported for a long time, closing the issue as it will not be resolved.
