### ISSUE TITLE
1.12.2 Optifine Random Entity Skin Broken

### ISSUE THREAD

**Issue by BredyAK** [chylex/Resource-Pack-Organizer#31]
I'm running Minecraft 1.12.2 forge with `OptiFine_1.12.2_HD_U_F5` and `Resource Pack Organizer Release 1.0.4`, and I find this mod will destroy Optifine's random-entity-texture function. Check this for more details: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties, we can add multi skins on folder `/assets/minecraft/optifine/random/entity/`, for example if I add `zombie2.png`, `zombie3.png` on folder `/assets/minecraft/optifine/random/entity/zombie/`, zombies will have random skins.

RPO will only destroy the random entity skin function, entity will just use its vanilla skin. Other parts of the resource pack work fine.

**Comment by chylex** [comment]
All versions of RPO before 1.15 needed hacks which aren't compatible with some other mods' hacks. 1.15 onwards work completely differently and don't have any issues, so for me it's not worth going back to very old versions and try to work around incompatibilies when new versions don't have them at all. If people want old versions fixed, the mod is open-source so they can always make a PR or release a fixed version on their own.

**Comment by BredyAK** [comment]
Thanks. Can you make 1.12.2 client compatible with the latest version of the mod? There are so many mods lost maintenance of their authors on 1.12.2 version, therefore I can't use the latest version mod. I really want this. Thanks!

**Comment by chylex** [comment]
1.12 and 1.15 are completely different, it's not possible.
