### ISSUE TITLE
Game Crashes when I open Resource Pack menu

### ISSUE THREAD

**Issue by GalaxyBlade** [chylex/Resource-Pack-Organizer#36]
My game crashes when I open the resource pack menu, and I can't put on a resourcepack because it crashes, are there any fixes for this?

I'm thinking it's because I have too many resourcepacks in my resourcepack folder.

MC Version: 1.7.10
Mod Version: Unknown

I can send the mod file I have if that would help to determine what version of the mod I have.

**Comment by chylex** [comment]
I don't support 1.7 anymore, you're on your own.
