### ISSUE TITLE
1.17+/1.18+/1.19+ support

### ISSUE THREAD

**Issue by RaptaG** [chylex/Resource-Pack-Organizer#38]
Is there going to be support for versions 1.17, 1.18 and 1.19?

**Comment by chylex** [comment]
I haven't looked at how 1.17/18 does resource packs. They changed it in 1.16 in a way that made it more annoying to develop the mod, so I'm not really interested in updating the mod atm.

**Comment by Bluscream** [comment]
I would also love to see a 1.18 version, thanks ^^

**Comment by itsMarkiS** [comment]
plzzzzz we need 1.18 update

**Comment by Tizooo** [comment]
#1.18 !!!

**Comment by realKeehan** [comment]
Would love 1.18.2 support

**Comment by RaptaG** [comment]
> Would love 1.18.2 support

Could you please not make comments because some people are waiting for that and have enabled the notifications to see if the dev actually makes an upload... You can just react with 👍🏽 on my 1st comment...

**Comment by Scarlaid** [comment]
Just commenting to bring this issue back alive

> No but all seriousness, this mod is just pure gem to find. The frustration trying to find a Resource Pack organizer is tough, for Fabric, at least, ever since Lunar Client has this similar "organizer", it just feel good to just go on whichever folder you want and choose your texture pack
> We all waited long for months, since the last reply was Dec 2021, but just please, update this mod to 1.18.x, it's just **that** good to let people hyped over the months passed, even with notification on.

**Comment by RaptaG** [comment]
> Just commenting to bring this issue back alive

Thanks for commenting

**Comment by Authiesz** [comment]
1.19 support when?

**Comment by RaptaG** [comment]
@Plushhh please https://github.com/chylex/Resource-Pack-Organizer/issues/38#issuecomment-1073003885

**Comment by e-splat** [comment]
i've tried to port the mod myself, but i don't have the knowledge for it :(

**Comment by RaptaG** [comment]
This issue has been active for ~1 year. Is there _any_ progress so far @chylex?

**Comment by chylex** [comment]
I'm not interested in spending time on this mod, so there will not be any progress from me. That includes potential PRs, since reviewing and testing PRs would also require my time. However, anyone is free to take the source code and release their own version according to the project's open-source license.

**Comment by RaptaG** [comment]
If anybody is willing to update this mod, please let me know in this issue.

**Comment by Bluscream** [comment]
Sorry, i have no clue about java, i only know C#, lua and python

**Comment by Scarlaid** [comment]
I suggest bringing this thread up the the Fabric Community Discord server, they might interested

**Comment by enjarai** [comment]
Hi there, this mod was indeed brought up in the fabric discord and it looked really cool, so I've been working on porting it. There were quite a few things that needed fixing, so it took me a while, but I'm pretty sure i've got the whole thing working on fabric 1.18.2 now. I'll put it up on github once I've polished it up a bit. 

@chylex would you mind me posting the port on curse/modrinth? There might be some small opinionated changes I make, so I'll publish it under a different name, with credit of course.

I should mention that I do not plan on making or maintaining a port of the forge version of this mod as I have no experience with the forge ecosystem.

![image](https://user-images.githubusercontent.com/38552516/189535075-bfc1fbda-5bc1-4786-ac25-d6334e895623.png)

**Comment by chylex** [comment]
> @chylex would you mind me posting the port on curse/modrinth? There might be some small opinionated changes I make, so I'll publish it under a different name, with credit of course.

Go ahead, that's why the mod is open source.

**Comment by enjarai** [comment]
> Go ahead, that's why the mod is open source.

Alright, asking just in case. Some devs can get really upset about these things. 😅 

I've uploaded the fork/port to my github at [enjarai/recursive-resources](https://github.com/enjarai/recursive-resources), anyone who wants it right now will have to build it themselves. It'll be going up on curse and modrinth within a day.

**Comment by RaptaG** [comment]
> I've uploaded the fork/port to my github at [enjarai/recursive-resources](https://github.com/enjarai/recursive-resources) [...]

Make sure to enable the issues section!

**Comment by enjarai** [comment]
> Make sure to enable the issues section!

Oh, that isnt there by default anymore? Enabled it just now.

**Comment by RaptaG** [comment]
Closing this issue, further discussions can be made here:
https://github.com/enjarai/recursive-resources/issues
