### ISSUE TITLE
I cannot scroll

### ISSUE THREAD

**Issue by Bloomer08** [chylex/Resource-Pack-Organizer#5]
So, the mod works perfectly fine untill i have to scroll down when selecting a resource pack. Is there any way to fix this? If not, then I guess I'll have to delete the mod. 

Version: 1.8.9
 Besides that I love the mod!

**Comment by chylex** [comment]
What's the mod version?

**Comment by Bloomer08** [comment]
The mod version of the actual mod is: 1.0.2 And i have tried it with, the forge recommended version and latest.

**Comment by chylex** [comment]
Update to 1.0.3.
