### ISSUE TITLE
cant even go on the recourse packs whn i use the mod

### ISSUE THREAD

**Issue by silentpots** [chylex/Resource-Pack-Organizer#6]
i cant go on recourse packs and it crashes my mc when trying to open it while using the mod while on 1.8 and 1.7.10 as i tryed to use them on both

**Comment by silentpots** [comment]
and i can go recourse packs when not using the mod

**Comment by chylex** [comment]
Need the crash report. Also 1.7.10/1.8 are no longer supported.

**Comment by chylex** [comment]
No response in a month, closing the issue as invalid.
