### ISSUE TITLE
Custom Sky textures don't seem to load.

### ISSUE THREAD

**Issue by tale-zero** [chylex/Resource-Pack-Organizer#7]
See title. Removing the mod fixes it.
Does the path for the custom sky textures change with this mod? Or does it just simply not work?

Minecraft Version: 1.11.2

Installed Mods:
![image](https://cloud.githubusercontent.com/assets/5509604/26553235/c5f56612-4458-11e7-833c-74d6087ce7d0.png)

(edit)
With the mod:
![image](https://cloud.githubusercontent.com/assets/5509604/26553345/313b2ee8-4459-11e7-98fd-46f00ee69c34.png)

Without the mod:
![image](https://cloud.githubusercontent.com/assets/5509604/26553380/52bc0d8a-4459-11e7-94dc-835ee912df8e.png)

**Comment by chylex** [comment]
Does the issue happen when you disable all other mods and only keep RPO with the resource pack?

**Comment by TaleZero** [comment]
Just the mod and Optifine.
![image](https://cloud.githubusercontent.com/assets/5509604/26557565/68c29448-4470-11e7-8206-ed200cf138d9.png)

Same but without Liteloader.
![image](https://cloud.githubusercontent.com/assets/5509604/26557596/95fd4f2a-4470-11e7-87c7-afce231db774.png)

**Comment by chylex** [comment]
So it's a conflict with Optifine? Not sure if I can do anything about that.

**Comment by TaleZero** [comment]
Even though I forgot about this Github issue, I think it is worth mentioning that the 1.8.9 build doesn't seem to be affected by this with Optifine enabled.

![image](https://user-images.githubusercontent.com/5509604/31963281-217184be-b8ce-11e7-912a-e552708c350f.png)

Guessing that something changed between 1.8.9 and 1.11.2. ¯\_(ツ)_/¯

**Comment by chylex** [comment]
The changes in RPO across those versions shouldn't have any effect on sky rendering, but I haven't looked into optifine (and probably won't, so the issue is staying open unless someone PRs a fix or at least figures out why it's happening).

**Comment by mgdgfbhevdyeh** [comment]
IDK how about this bug,but looks with this mod I play the game the render distance is locked to 2 or 4.

**Comment by sheenwins** [comment]
I'm having the same issue and these are my two favorite mods. :/  I can confirm that using forge 1.8.9, adding in ResourcePackOrganizer  MC-1.8.9  v1.0.3.jar breaks custom skies.
Any update on this?

**Comment by chylex** [comment]
No updates on the issue, sorry. Is there an alternative sky mod you could try?

**Comment by sheenwins** [comment]
I tried a few, same issue :/  I edited my comment with the path to the sky
files.  all resource packs I try have the files under mcpatcher.  was
hoping that would guide you in the right direction for a resolution :)

**Comment by nozuo** [comment]
Hi,Sky textures don't seem to load. Minecraft version 1.11.2.

**Comment by Mizig** [comment]
Version 1.0.0 works fine with optifine skies, but 1.0.1 and on do not.
Which is a shame, because it appears you are unable to scroll the resource pack menu in 1.0.0...

**Comment by chylex** [comment]
Since 1.15 was a complete rewrite that took advantage of many built-in vanilla mechanics, and it doesn't require any hacky workarounds that were needed in 1.12 and likely caused this issue, my recommendation is to try 1.15.

Due to the hackiness of 1.12 and older, I'm not planning to update these versions.
